# syntax=docker/dockerfile:1.7
#
# CPU image — Ubuntu base + PyTorch CPU wheels + the three forecasters.
# linux/amd64 only — pytorch.org's CPU index ships torch==2.4.1+cpu wheels for
# linux_x86_64 + win_amd64; no manylinux aarch64 wheel at this pinned version.
#
# Heavy ML deps are installed explicitly in the runtime stage, not via
# `uv sync`, because torch's --index-url and timesfm's git-only release make
# uv.lock unable to pin both CPU and CUDA images from one lockfile.

FROM python:3.12-slim-bookworm@sha256:d193c6f51a7dbd10395d6328de3a7edb0516fb0608ca138036576f574c3e07d2 AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.11.15@sha256:e590846f4776907b254ac0f44b5b380347af5d90d668138ca7938d1b0c2f98d3 /uv /usr/local/bin/uv

WORKDIR /app

# 1) Lightweight runtime deps from uv.lock (fastapi, uvicorn, pydantic, mcp,
#    huggingface-hub, numpy). Frozen install — fails if the lock is stale.
COPY pyproject.toml uv.lock* ./
COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev || uv sync --no-dev

# 2) Heavy ML deps — installed with --require-hashes from a hash-locked
#    requirements file. Generated by `make deps-lock` from
#    scripts/deps.in. Any post-publish wheel hijack fails the hash
#    check at install time. Includes torch (CPU build, via uv's
#    --torch-backend=cpu during the compile step).
COPY requirements-cpu.txt ./
# torch+cpu wheels live on pytorch.org's CPU index, not PyPI.
# Two flags worth explaining:
#   --no-config: ignore the cwd's pyproject.toml at install. Reason: it
#       has `[tool.uv] exclude-newer = "<date>"` which filters wheels by
#       upload date — but pytorch.org's PEP-503 simple index doesn't
#       expose dates, so undated torch wheels get excluded → "version
#       not found". The age gate is still enforced at LOCKFILE GENERATION
#       time (`make deps-lock` runs uv pip compile *with* the gate);
#       at install time it's redundant because the lockfile already pinned
#       pre-cutoff versions + the hashes verify the exact bytes.
#   --index-strategy unsafe-best-match: uv's default refuses to look at a
#       secondary index for a package found on the primary (dependency-
#       confusion protection). Both pytorch.org and pypi.org are explicit,
#       TLS-signed, equally-trusted registries here — protection is moot.
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --python /opt/venv/bin/python \
        --no-config \
        --require-hashes \
        --extra-index-url https://download.pytorch.org/whl/cpu \
        --index-strategy unsafe-best-match \
        -r requirements-cpu.txt

# 3) timesfm has no PyPI release for 2.5 — install from git with a pinned SHA.
#    --no-deps because it pulls in tf-related deps we don't need (we use the
#    torch backend only). Git SHA pinning is the integrity check; no hash
#    file is needed (or supported) for VCS installs.
ARG TIMESFM_REF=d720daa6786539c2566a44464fbda1019c0a82c0
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --python /opt/venv/bin/python --no-deps \
        "timesfm[torch] @ git+https://github.com/google-research/timesfm.git@${TIMESFM_REF}"

# 4) Toto-1 (Datadog/Toto-Open-Base-1.0). The toto-ts package on PyPI pins
#    torch==2.7.0 + transformers==4.52.1 + gluonts==0.15.1, all conflicting
#    with our chronos/uni2ts pins. Verified to actually work against our
#    torch 2.4.1 + transformers 4.57.6 + gluonts 0.14.4, so install with
#    --no-deps. rotary-embedding-torch + jaxtyping are the only real
#    runtime deps not already in our stack.
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --python /opt/venv/bin/python --no-deps \
        "toto-ts==0.1.4" \
        "rotary-embedding-torch==0.8.6" \
        "jaxtyping==0.2.29"

# 5) Sundial sidecar venv — separate /opt/sundial-venv with its own
#    transformers==4.40.1 because sundial's published model code uses
#    DynamicCache internals removed in transformers 4.42+. Shimming those
#    from the outside breaks deep inside transformers itself, so we run
#    sundial in its own venv with its required transformers and proxy from
#    the main service over a unix socket.
#
#    Fresh full venv (~2GB additional image cost). Symlinks back to the
#    main venv's torch/numpy were attempted but uv's resolver clobbers
#    them on dep updates, breaking numpy ABI compatibility. Honest cost.
RUN python -m venv /opt/sundial-venv

COPY requirements-sundial.txt ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --python /opt/sundial-venv/bin/python \
        --no-config \
        --index-url https://download.pytorch.org/whl/cpu \
        --index-strategy unsafe-best-match \
        "torch==2.4.1" \
    && uv pip install --python /opt/sundial-venv/bin/python \
        --no-config \
        -r requirements-sundial.txt

# Worker code (gets started by entrypoint.sh as a background process on
# /tmp/predictalot/sundial.sock).
COPY --chown=predictalot:predictalot sundial_worker /opt/sundial_worker

# -----------------------------------------------------------------------------
FROM python:3.12-slim-bookworm@sha256:d193c6f51a7dbd10395d6328de3a7edb0516fb0608ca138036576f574c3e07d2 AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/opt/venv/bin:$PATH" \
    PYTHONPATH=/app/src \
    TZ=UTC \
    PREDICTALOT_HOST=0.0.0.0 \
    PREDICTALOT_PORT=8080 \
    PREDICTALOT_MODEL_DIR=/models \
    PREDICTALOT_DEVICE=auto

RUN apt-get update && apt-get install -y --no-install-recommends \
        libgomp1 \
    && rm -rf /var/lib/apt/lists/* \
    && (userdel -r ubuntu 2>/dev/null || true) \
    && useradd -u 1000 --create-home --shell /bin/bash predictalot \
    && mkdir -p /models \
    && chown predictalot:predictalot /models

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
COPY --from=builder /opt/sundial-venv /opt/sundial-venv
COPY --from=builder --chown=predictalot:predictalot /opt/sundial_worker /opt/sundial_worker
COPY --chown=predictalot:predictalot src ./src
COPY --chown=predictalot:predictalot pyproject.toml ./
COPY --chown=predictalot:predictalot entrypoint.sh /usr/local/bin/predictalot-entrypoint
RUN chmod +x /usr/local/bin/predictalot-entrypoint

USER predictalot

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python -c "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8080/healthz').status==200 else 1)" || exit 1

ENTRYPOINT ["/usr/local/bin/predictalot-entrypoint"]
